site_name: Pomodoro
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        name: Switch to light mode
        icon: material/lightbulb-outline
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        name: Switch to dark mode
        icon: material/lightbulb
  features:
    - toc.follow
    - navigation.top
    - navigation.tracking
    - search.highlight
    - content.tabs.link
repo_url: https://github.com/yemaney/pomodoro
repo_name: yemaney/pomodoro
